name: dbt CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install dbt-core dbt-snowflake great-expectations

      - name: Run dbt deps
        run: dbt deps

      - name: dbt Build & Test
        run: dbt build --select +fct_sales

      - name: Run Great Expectations
        run: great_expectations checkpoint run orders_checkpoint
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          # Add other secrets
